// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	models "projects/LDmitryLD/parser/app/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// VacancyStorager is an autogenerated mock type for the VacancyStorager type
type VacancyStorager struct {
	mock.Mock
}

// Create provides a mock function with given fields: vacs
func (_m *VacancyStorager) Create(vacs []models.Vacancy) {
	_m.Called(vacs)
}

// Delete provides a mock function with given fields: id
func (_m *VacancyStorager) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields:
func (_m *VacancyStorager) List() ([]models.Vacancy, error) {
	ret := _m.Called()

	var r0 []models.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Vacancy, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Vacancy); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: query
func (_m *VacancyStorager) Search(query string) ([]models.Vacancy, error) {
	ret := _m.Called(query)

	var r0 []models.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.Vacancy, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []models.Vacancy); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByID provides a mock function with given fields: id
func (_m *VacancyStorager) SearchByID(id int) (models.Vacancy, error) {
	ret := _m.Called(id)

	var r0 models.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Vacancy, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Vacancy); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Vacancy)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVacancyStorager creates a new instance of VacancyStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVacancyStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *VacancyStorager {
	mock := &VacancyStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
